### ISSUE TITLE
Util for saving and loading `ConvNP`

### ISSUE THREAD

**Issue by tom-andersson** [tom-andersson/deepsensor#11]
Currently, between Python sessions, users need to re-instantiate the exact same model object before loading pre-trained weights. (I believe there are ways to save model arch information with TF/PyTorch to auto-build models, but I don't *think* `neuralprocesses` supports this, cc @wesselb).

This means the exact call signature for `nps.construct_convgnp` (containing model hypers) needs to be used, which introduces two potential causes for users not being able to re-instantiate their models:
* the user forgets or loses the model architecture details
* the default model arch settings change in `deepsensor`

I propose two new methods in `deepsensor.nps` for saving and loading `ConvNP` objects. These would take a folder as input and either save or load the model weights *and* the call signature used for constructing the model.

**Comment by tom-andersson** [comment]
Thanks for getting back to me @wesselb!

In the PyTorch case, with `torch.save(model, fpath)`, I get:
```
TypeError: cannot pickle 'module' object
```
This is weird, because online this is meant to work. `model` is type `neuralprocesses.torch.Model`.

In the TF case, with `model.save` I get (this is after compiling the model by running it with data):
```
cannot be saved either because the input shape is not available or because the forward pass of the model is not defined.To define a forward pass, please override `Model.call()`. To specify an input shape, either call `build(input_shape)` directly, or call the model on actual data using `Model()`, `Model.fit()`, or `Model.predict()`. If you have a custom training step, please make sure to invoke the forward pass in train step through `Model.__call__`, i.e. `model(inputs)`, as opposed to `model.call()`.
```

I think rather than saving the entire model (e.g. with pickle in the `torch` case), it's safer to have the model be re-instantiated before loading weights, e.g. as suggested in the OP.

**Comment by wesselb** [comment]
Hmmm... Okay, maybe the import magic is getting in the way of this just working. Perhaps it isn't as simple as just `torch.save` / `model.save` :(.

**Comment by RohitRathore1** [comment]
Hi @tom-andersson @wesselb,
Thanks for the nice description. To proceed with implementing the save and load methods, we need to make a few decisions:
- Storage Format: Decide on a storage format for saving the model weights and the call signature. Common formats include JSON for metadata (like the call signature) and `.pth` or `.h5` for PyTorch or TensorFlow model weights, respectively.
- Folder Structure: Decide how to structure the contents in the provided folder. For example:
a) metadata.json: Contains the call signature and other metadata.
b) weights.pth or weights.h5: Contains the model weights.

**Comment by tom-andersson** [comment]
`ConvNP` now has a `.save(folder)` method and can be re-initialised (with the same architecture and weights) using `ConvNP(folder)` or `ConvNP(data_processor, task_loader, folder)`:  https://github.com/tom-andersson/deepsensor/commit/b7f14c30afa4508d4fca242a27df20a5bc0f97db

Thanks for your thoughts above @RohitRathore1, they were helpful :)
