### ISSUE TITLE
Error with task plotting

### ISSUE THREAD

**Issue by kenzaxtazi** [tom-andersson/deepsensor#17]
I'm running into an issue plotting the task

I've load the following spatial interpolation task:

`time: 2002-10-08 22:59:59.999321216
flag: None
X_c: [(2, 324), ((1, 57), (1, 57))]
Y_c: [(1, 324), (1, 57, 57)]
X_t: [((1, 57), (1, 57))]
Y_t: [(1, 57, 57)]`

which matches the dimensions of the original notebook. However I get the following message when I call:

`fig = context_encoding(model, task, task_loader)
plt.show()'

`
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[85], line 1
----> 1 fig = context_encoding(model, task, task_loader)
      2 plt.show()

File [~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/plot.py:53](https://file+.vscode-resource.vscode-cdn.net/Users/kenzatazi/Documents/CDT/Code/mfdgp/deepsensor/~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/plot.py:53), in context_encoding(model, task, task_loader, batch_idx, context_set_idxs, land_idx, cbar, clim, cmap, verbose_titles, titles, size, return_axes)
     25 """Plot the encoding of a context set in a task
     26 
     27 Parameters
   (...)
     49     Whether to return the axes of the figure, by default False
     50 """
     51 from .model.nps import compute_encoding_tensor
---> 53 encoding_tensor = compute_encoding_tensor(model, task)
     54 encoding_tensor = encoding_tensor[batch_idx]
     56 if isinstance(context_set_idxs, int):

File [~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/model/nps.py:189](https://file+.vscode-resource.vscode-cdn.net/Users/kenzatazi/Documents/CDT/Code/mfdgp/deepsensor/~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/model/nps.py:189), in compute_encoding_tensor(model, task)
    187 def compute_encoding_tensor(model, task: Task):
    188     neural_process_encoder = backend.nps.Model(model.model.encoder, lambda x: x)
--> 189     task = model.check_task(task)
    190     encoding = B.to_numpy(run_nps_model(neural_process_encoder, task))
    191     return encoding

File [~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/model/convnp.py:191](https://file+.vscode-resource.vscode-cdn.net/Users/kenzatazi/Documents/CDT/Code/mfdgp/deepsensor/~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/model/convnp.py:191), in ConvNP.check_task(cls, task)
    189 """Check that the task is compatible with the model."""
    190 if task["flag"] is None:
--> 191     task = cls.modify_task(task)
    192 elif task["flag"] != "NPS":
    193     raise ValueError(f"Task has been modified for {task['modify']}.")

File [~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/model/convnp.py:184](https://file+.vscode-resource.vscode-cdn.net/Users/kenzatazi/Documents/CDT/Code/mfdgp/deepsensor/~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/model/convnp.py:184), in ConvNP.modify_task(cls, task)
    180         arr = backend.nps.Masked(arr, B.cast(B.dtype(arr), mask))
    182     return arr
--> 184 task = task.modify(array_modify_fn, modify_flag="NPS")
    185 return task

File [~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/data/task.py:105](https://file+.vscode-resource.vscode-cdn.net/Users/kenzatazi/Documents/CDT/Code/mfdgp/deepsensor/~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/data/task.py:105), in Task.modify(self, f, modify_flag)
    103 self = copy.deepcopy(self)  # don't modify the original
    104 for k, v in self.items():
--> 105     self[k] = modify(k, v)
    106 self["flag"] = modify_flag
    108 return self

File [~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/data/task.py:95](https://file+.vscode-resource.vscode-cdn.net/Users/kenzatazi/Documents/CDT/Code/mfdgp/deepsensor/~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/data/task.py:95), in Task.modify..modify(k, v)
     93     return v
     94 if type(v) is list:
---> 95     return [modify(k, vi) for vi in v]
     96 elif type(v) is tuple:
     97     return (modify(k, v[0]), modify(k, v[1]))

File [~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/data/task.py:95](https://file+.vscode-resource.vscode-cdn.net/Users/kenzatazi/Documents/CDT/Code/mfdgp/deepsensor/~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/data/task.py:95), in (.0)
     93     return v
     94 if type(v) is list:
---> 95     return [modify(k, vi) for vi in v]
     96 elif type(v) is tuple:
     97     return (modify(k, v[0]), modify(k, v[1]))

File [~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/data/task.py:99](https://file+.vscode-resource.vscode-cdn.net/Users/kenzatazi/Documents/CDT/Code/mfdgp/deepsensor/~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/data/task.py:99), in Task.modify..modify(k, v)
     97     return (modify(k, v[0]), modify(k, v[1]))
     98 elif type(v) is np.ndarray:
---> 99     return f(v)
    100 else:
    101     return v

File [~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/model/convnp.py:173](https://file+.vscode-resource.vscode-cdn.net/Users/kenzatazi/Documents/CDT/Code/mfdgp/deepsensor/~/Documents/CDT/Code/mfdgp/deepsensor/deepsensor/model/convnp.py:173), in ConvNP.modify_task..array_modify_fn(arr)
    170 mask = np.any(np.isnan(arr), axis=1, keepdims=False)
    171 if np.any(mask):
    172     # Set NaNs to zero - necessary for `neural_process`
--> 173     arr[mask] = 0.0
    175 # Convert to tensor object based on deep learning backend
    176 arr = backend.convert_to_tensor(arr)

IndexError: boolean index did not match indexed array along dimension 1; dimension is 1 but corresponding boolean dimension is 324'

**Comment by tom-andersson** [comment]
Thank you for raising this @kenzaxtazi. As discussed on Slack, this bug is actually because there are NaNs in your context data. This is intended to be supported by the `ConvNP` model by converting the context observations to an `nps.Masked` object which masks out the NaNs.

... however, you were then bumping into a bug where `keepdims=False` should have been `True` when masking NaNs in the context data, fixed in https://github.com/tom-andersson/deepsensor/commit/c94936312dcd67a23c754410a83fc2093e87cfee

Over Slack you mentioned fixing this revealed *another* error from the way the `Task` was being converted to arguments for running a `neuralprocesses` model when that `Task` contained an `nps.Masked` object. This has now been fixed via a small overhaul of this conversion process that now means predicting multiple target sets at different locations is supported: https://github.com/tom-andersson/deepsensor/commit/36942c3575b97e0697ccb0e236d7e713ca18e9ab

I'll close this now as unit tests are passing on `main` with a new test that the model runs with NaNs in the context data: https://github.com/tom-andersson/deepsensor/blob/64caf35fe86f91266c21d81a8792cad3bdd42bfa/tests/test_model.py#L259-L270
