### ISSUE TITLE
`cartopy` package is required for all the tutorials but is not in any of the requirements 

### ISSUE THREAD

**Issue by magnusross** [tom-andersson/deepsensor#26]
Very minor issue, pretty self explanatory, the `cartopy` package is used in all the tutorials but doesn't seem to be in any of the requirements, as such the tutorials fail to run without an additional install.

**Comment by JimCircadian** [comment]
I agree with your points here @tom-andersson, the demonstrator notebooks shouldn't be in python package source codebase, it tends to cause more problems than it's worth 😉

**Comment by acocac** [comment]
> I agree with your points here @tom-andersson, the demonstrator notebooks shouldn't be in python package source codebase, it tends to cause more problems than it's worth 😉

💯
