### ISSUE TITLE
Support active learning with `Y_t_aux` downscaling functionality

### ISSUE THREAD

**Issue by tom-andersson** [tom-andersson/deepsensor#34]
Currently only the `X_t` key in `Task`s are overwritten during active learning, but `Y_t_aux` must be as well or else an error is raised. See below:

https://github.com/tom-andersson/deepsensor/blob/a906796887ad3cf894c2aa439ed19705d71741eb/deepsensor/active_learning/algorithms.py#L428-L439

Since `Y_t_aux` can only come from sampling with a `task_loader`, we require `task_loader` to be passed to the `GreedyAlgorithm`, as for the `AcquisitionFunctionOracle` case.

E.g.:
```
            if task_loader is not None and task_loader.aux_at_target_dims > 0:
                tasks[i]["Y_t_aux"] = task_loader.sample_aux_t(self.X_t_arr)
```

We'd also need to raise an error ahead of time if the model expects `Y_t_aux` data but a `TaskLoader` isn't provided to `GreedyAlgorithm`.

**Comment by RohitRathore1** [comment]
Alright, it seems you are trying to modify the existing code to ensure that `Y_t_aux` gets updated during active learning. If my understanding is correct, you want to make sure:

- If `task_loader` is provided and `task_loader.aux_at_target_dims > 0`, then the `Y_t_aux` in tasks is updated.
- If the model expects `Y_t_aux` data and `task_loader` is not provided, an error should be raised.

So the PR #35 solves the following issue.

**Comment by tom-andersson** [comment]
Thank you @RohitRathore1! PR merged and tests are passing on `main`, so I'll close this now.
