### ISSUE TITLE
Documentation Page

### ISSUE THREAD

**Issue by nilsleh** [tom-andersson/deepsensor#44]
I was wondering if there are plans to add a documentation page like sphinx-documentation to make it easier to navigate the different pieces of the library? If not and it is something you are interested in, I could open a PR :)

**Comment by tom-andersson** [comment]
Hi @nilsleh, thank you for opening this. It's very high on our priority list to set up documentation. Don't worry about a PR just yet - given that I've written most of the code so far and things are starting to stabilise, I'm planning to finish writing docstrings ASAP so we can set up sphinx. It will then be simpler for others to start contributing, either to the code itself or the documentation.

**Comment by kallewesterling** [comment]
Thank you so much for offering help, @nilsleh. There's some work towards this taking place in the [add-documentation branch](https://github.com/tom-andersson/deepsensor/tree/add-documentation).

**Comment by kallewesterling** [comment]
@nilsleh We have an early first look at the documentation live at https://tom-andersson.github.io/deepsensor. We're planning to add some information about how to contribute to the documentation as well, and I think I speak for both myself and Tom when I say that we would really appreciate contributions here. Example notebooks/scripts/tutorials is definitely something we'd appreciate. Is that something you'd be interested in helping with?

**Comment by kallewesterling** [comment]
@nilsleh We have an early first look at the documentation live at https://tom-andersson.github.io/deepsensor. We're planning to add some information about how to contribute to the documentation as well, and I think I speak for both myself and Tom when I say that we would really appreciate contributions here. Example notebooks/scripts/tutorials is definitely something we'd appreciate. Is that something you'd be interested in helping with?

**Comment by nilsleh** [comment]
@kallewesterling Yes, certainly, I'd be happy to help with anything you deep interesting in that space! So just let me know :)

**Comment by tom-andersson** [comment]
Closing as we now have the documentation page up and running here: https://tom-andersson.github.io/deepsensor/

Still need to write the introductory pages and short notebook demonstrators! Our first notebook-rendered example is here: https://tom-andersson.github.io/deepsensor/getting-started/tutorials/quickstart.html
