### ISSUE TITLE
Discussions tab?

### ISSUE THREAD

**Issue by patel-zeel** [tom-andersson/deepsensor#46]
Hi @tom-andersson and @kallewesterling,

Would it be useful to enable the `Discussions` tab to discuss some ideas and suggestions?

**Comment by kallewesterling** [comment]
Thank you for your suggestion @patel-zeel -- it's a good one! Was there any use case you had in mind? I like to keep issues as a way to formally have feature requests, bug fixes, etc. documented, and the ability to add them to our internal project management board. But I can imagine other use cases for the Discussions tab. Was there anything in particular you had in mind?

**Comment by patel-zeel** [comment]
Thank you for your response, @kallewesterling. Here is what I had in mind. As per my discussion with @tom-andersson, I was planning to check if it'd be useful to have a `deepsensor` community channel on Slack. For similar discussions, is the discussion tab better suited than issues?

**Comment by tom-andersson** [comment]
Hi @patel-zeel, we're working on setting up a Slack community and will keep you in the loop - we'll also discuss your idea of a Discussions tab - thanks!

**Comment by tom-andersson** [comment]
Closing because our Slack community now satisfies the functionality of discussing ideas/suggestions.
