### ISSUE TITLE
Add contributors using `all-contributors`

### ISSUE THREAD

**Issue by tom-andersson** [tom-andersson/deepsensor#58]
Issue for using the `all-contributors` bot to acknowledge people's contributions.

Bot usage: https://allcontributors.org/docs/en/bot/usage

Emoji key: https://allcontributors.org/docs/en/emoji-key

**Comment by tom-andersson** [comment]
@all-contributors
please add @tom-andersson for code.
please add @kallewesterling for code.

**Comment by tom-andersson** [comment]
@all-contributors please add @kallewesterling for doc

**Comment by tom-andersson** [comment]
@all-contributors please add @tom-andersson for research, maintenance, bug, test, tutorial, doc, review, talk, question

**Comment by tom-andersson** [comment]
@all-contributors please add @kallewesterling for infra, ideas, projectManagement, promotion, answering questions

**Comment by tom-andersson** [comment]
@all-contributors please add @acocac for userTesting, bug, mentoring, ideas

**Comment by tom-andersson** [comment]
@all-contributors please add @acocac for research

**Comment by tom-andersson** [comment]
@all-contributors please add @wesselb for research, code, ideas

**Comment by tom-andersson** [comment]
@all-contributors please add @scotthosking for fundingFinding, ideas, projectManagement

**Comment by tom-andersson** [comment]
@all-contributors please add @patel-zeel for bug, code, userTesting, ideas

**Comment by tom-andersson** [comment]
@all-contributors please add @jonas-scholz123 for userTesting, research, code, bug, ideas

**Comment by tom-andersson** [comment]
@all-contributors please add @nilsleh for ideas, userTesting, bug

**Comment by tom-andersson** [comment]
@all-contributors please add @kenzaxtazi for ideas

**Comment by tom-andersson** [comment]
@all-contributors please add @polpel for userTesting, bug

**Comment by tom-andersson** [comment]
@all-contributors please add @RohitRathore1 for code

**Comment by tom-andersson** [comment]
@all-contributors please add @magnusross for tutorial, data

**Comment by tom-andersson** [comment]
Closing this now because I've captured most DeepSensor contributions to date. To add future contributions we can use the `all-contributors` bot in context within issues/PRs. For contributions without a corresponding issue/PR (such as non-code contributions), we can continue using the bot in this issue.

**Comment by kallewesterling** [comment]
Thank you!

**Comment by tom-andersson** [comment]
@all-contributors please add @annavaughan for research

**Comment by tom-andersson** [comment]
@all-contributors please add @ots22 for ideas

**Comment by tom-andersson** [comment]
@all-contributors please add @davidwilby for bug

**Comment by tom-andersson** [comment]
@all-contributors please add @davidwilby for bug

**Comment by tom-andersson** [comment]
@all-contributors please add @davidwilby for bug

**Comment by tom-andersson** [comment]
Note to self: @all-contributors calls need to be added to issues (like this one) so that the bot's automatic PR is forked from the latest commit in `main`. If done from a PR the bot can be behind `main`, leading to merge conflicts.
