### ISSUE TITLE
Replace example data with open-source data

### ISSUE THREAD

**Issue by tom-andersson** [tom-andersson/deepsensor#8]
Currently, the example notebooks in `notebooks/` load data from my local environment. It would be good to replace these examples with open-source versions, such as:
```
ds_raw = xr.tutorial.open_dataset("air_temperature")
```

We would need equivalents to the above for pandas station data as well as auxiliary fields like elevation and a land mask, which may be tricky.

**Comment by acocac** [comment]
List of some potential open meteorological and climate dataset:
- [MeteoNet](https://meteofrance.github.io/meteonet/)

**Comment by tom-andersson** [comment]
Closing as this now pertains to the DeepSensor Gallery - have moved issue to that repo here https://github.com/tom-andersson/deepsensor_gallery/issues/2.
